"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const todoItem_class_1 = require("./classes/todoItem.class");
const todoList_class_1 = require("./classes/todoList.class");
let myList = new todoList_class_1.TodoList();
myList.addItem(new todoItem_class_1.TodoItem(1, 'Elmenni kenyérért a boltba'));
myList.addItem(new todoItem_class_1.TodoItem(2, 'Elmenni tejért a boltba'));
myList.addItem(new todoItem_class_1.TodoItem(3, 'Elmenni vajért a boltba'));
myList.addItem(new todoItem_class_1.TodoItem(4, { task: 'Orvosi időpontra menni', date: new Date('2024-10-06') }));
myList.addItem(new todoItem_class_1.TodoItem(4, { task: 'Nyaralásra menni', date: new Date('2024-12-03') }));
//myList.deleteItem(2);
//console.log(myList);
myList.listItems();
